if __name__ == '__main__':
    equipmentCodes = ["J4-BC-014",
                      "J4-BC-001",
                      "J4-BC-003",
                      "J4-BC-004",
                      "J4-BC-008",
                      "J4-BC-017",
                      "J4-BC-018",
                      "J4-BC-024",
                      "J4-BC-029",
                      "J4-BC-030",
                      "J4-BC-031",
                      "J4-BC-032",
                      "J4-BC-033",
                      "J4-BC-034",
                      "J4-BC-038",
                      "J4-BC-041",
                      "J4-BC-053",
                      "JBS-4-ZS-01",
                      "JBS-4-ZS-02",
                      "JBS-4-ZS-03",
                      "JBS-4-ZS-04",
                      "JBS-4-ZS-05",
                      "JBS-4-ZS-06",
                      "JBS-4-ZS-07",
                      "JBS-4-ZS-08",
                      "JBS-4-ZS-09",
                      "JBS-4-ZS-10",
                      "JBS-4-ZS-11",
                      "JBS-4-ZS-12",
                      "JBS-4-ZS-13",
                      "JBS-4-ZS-14",
                      "JBS-4-ZS-15",
                      "JBS-4-ZS-16",
                      "JBS-4-ZS-17",
                      "JBS-4-ZS-18",
                      "JBS-4-ZS-19",
                      "JBS-4-ZS-20",
                      "JBS-4-ZS-21",
                      "JBS-4-ZS-22",
                      "JBS-4-ZS-23",
                      "JBS-4-ZS-24",
                      "JBS-4-ZS-25",
                      "JBS-4-ZS-26",
                      "JBS-4-ZS-27",
                      "JBS-4-ZS-28",
                      "JBS-4-ZS-29",
                      "JBS-4-ZS-30",
                      "JBS-4-ZS-31",
                      "JBS-4-ZS-32",
                      "JBS-4-ZS-33",
                      "JBS-4-ZS-34",
                      "JBS-4-ZS-35",
                      "JBS-4-ZS-36",
                      "JBS-4-ZS-37",
                      "JBS-4-ZS-38",
                      "JBS-4-ZS-39",
                      "JBS-4-ZS-40",
                      "JBS-4-ZS-41",
                      "JBS-4-ZS-42",
                      "JBS-4-ZS-43",
                      "JBS-4-ZS-44",
                      "JBS-4-ZS-45",
                      "JBS-4-ZS-46",
                      "JBS-4-ZS-47",
                      "JBS-4-ZS-48",
                      "JBS-4-ZS-49",
                      "JBS-4-ZS-50",
                      "JBS-4-ZS-51",
                      "JBS-4-ZS-52",
                      "JBS-4-ZS-53"]
    updateSql = "update mes_pms.equipment set draw_x = {draw_x} ,draw_y = {draw_y} where equipment_code = '{equipment_code}';"
    for i in range(0, len(equipmentCodes)):
        row = int((i / 8)) + 1
        col = i % 8 + 1
        print(updateSql.format(draw_x=col * 10, draw_y=row * 8, equipment_code=equipmentCodes[i]))
